### ISSUE TITLE
More targets than list items (terminal vim)

### ISSUE THREAD

**Issue by akinsho** [davidklsn/vim-sialoquent#1]
Hi, thanks for an amazing vim theme, which is really cool. I have it working on macvim and just tried it in terminal vim and am getting the following error:

<img width="783" alt="screenshot 2017-02-27 19 28 37" src="https://cloud.githubusercontent.com/assets/22454918/23376378/c42c441c-fd23-11e6-89fe-797bd26136b2.png">

Which is actually in a launched but not visible instance of vim if I clear the screen It shows more of the themes background but vim does not load properly. I'm using terminal vim version 8.0
Inside Tmux version 2.3 (the issue occurs regardless of whether I use Tmux)
iTerm 2 build 3.0.14
Installed with Vundler

When I'm in vim and switch to sialoquent it loads when I source my config, this only happens on load. I've put a mini config below:

```
if !has('gui_running')
  set term=screen-256color "This is for Tmux
endif


if has('termguicolors')
  set termguicolors


  " set vim-specific sequences for rgb colors
  "truecolor support in vim
  let &t_8f = "\<esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<esc>[48;2;%lu;%lu;%lum"
endif

colorscheme sialoquent
```

Lemme know if I can provide any info, I'd appreciate any help you provide.

**Comment by davidklsn** [comment]
Hey! thanks ! Sry for the late response!

Do you still have an issue with this?

I am using Iterm2 3.0.14 but I can't replicate the issue

Could it be a plugin that is the issue?

**Comment by akinsho** [comment]
I'll try it with a minimal vimrc and get back to you but so far I haven't had this issue before

**Comment by akinsho** [comment]
Hi 

So i've just given it a try after rejiggering my plugins and its working! sorry for all the hassle turns out it was my setup, thanks again for the cool theme

**Comment by davidklsn** [comment]
Good to hear that you got it working! Thanks !

Have a great week!
